stages:
  - export
  - deploy

web:
  image: barichello/godot-ci:3.3
  stage: export
  variables:
    EXPORT_NAME: DataCity
  script:
    - mkdir -v -p build/web
    - godot -v --export "HTML5" ./build/web/index.html
    # bidouille pour avoir une ligne dans les logs nginx à chaque affichage de la page
    - sed -i '/<\/script>/i fetch("/?" + Date.now());' ./build/web/index.html
    - echo "Build ${CI_COMMIT_SHORT_SHA} / $(date)" > ./build/web/infos.txt
  artifacts:
    paths:
      - build/web
    expire_in: 1 day

deploy:
  stage: deploy
  needs:
    - job: web
      artifacts: true
  script:
    - |
      ssh -o StrictHostKeyChecking=no ${SSH_DEPLOY_TARGET} "
        rm -rf ~/datacity_new
        mkdir -p ~/datacity_new
      "
      scp -o StrictHostKeyChecking=no build/web/* "${SSH_DEPLOY_TARGET}:~/datacity_new"
      ssh -o StrictHostKeyChecking=no ${SSH_DEPLOY_TARGET} "
        rm -rf /opt/datacity/*
        mv ~/datacity_new/* /opt/datacity/
        rmdir ~/datacity_new
      "
  when: manual
