stages:
  - export
  - image
  - deploy

variables:
  http_proxy: http://pro01.sib.fr:3128
  https_proxy: http://pro01.sib.fr:3128
  no_proxy: sib.fr

web:
  image: barichello/godot-ci:3.3
  stage: export
  variables:
    EXPORT_NAME: DataCity
  script:
    - mkdir -v -p build/web
    - godot -v --export "HTML5" ./build/web/index.html
    # bidouille pour avoir une ligne dans les logs nginx à chaque affichage de la page
    - sed -i '/<\/script>/i fetch("/?" + Date.now());' ./build/web/index.html
  artifacts:
    paths:
      - build/web
    expire_in: 15 min


build-image:
  stage: image
  variables:
      IMAGE: $DOCKER_REGISTRY_DEV/data-city:latest
  script:
    - docker build . -t $IMAGE
    - docker push $IMAGE

deploy:
  stage: deploy
  dependencies: []
  script:
    - |
      ssh ${SSH_TARGET} "
        export DOCKER_REGISTRY_DEV=${DOCKER_REGISTRY_DEV}
        docker network create -d overlay --attachable data-city-network || true
        docker stack deploy --compose-file - serious-game
      " < docker-compose.yml
