version: '3.7'

networks:
  default:
    external: true
    name: data-city-network

services:
  data-city:
    image: $DOCKER_REGISTRY_DEV/data-city:main
    ports:
      - "60004:80"
    deploy:
      mode: replicated
      replicas: 1
